---
docker_prereqs_packages:
- apt-transport-https
- ca-certificates
- curl
- gnupg-agent
- software-properties-common

docker_packages:
- docker-ce
- docker-ce-cli
- containerd.io

docker_cgroup: |
      sudo mkdir /etc/docker
      cat <<EOF | sudo tee /etc/docker/daemon.json
      {
      "exec-opts": ["native.cgroupdriver=systemd"],
      "log-driver": "json-file",
      "log-opts": {
      "max-size": "100m"
      },
      "storage-driver": "overlay2"
      }
      EOF