
version: 2.1
kind: pipeline
type: docker
name: k8s-cluster

jobs:
  exec:
    docker:
      - image: brenom2k/brenolatest:latest
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: sa-east-1

    steps:
      - checkout
      - run:
          name: "Switch directory"
          command: "cd k8s-projeto-continuo"
steps: 
    - run:
      name: "terraform"
      command: "terraform init"

exec:
  docker:
    - image: brenom2k/brenolatest:latest

  steps:
      - run:
        name: "Terraform apply"
        command: "terraform apply -auto-approve"
  
  exec:
    docker:
      - image: brenom2k/brenolatest:latest
    steps:
      - run:
        name: "ansible-playbook -u ubuntu -i ec2.py site.yml"

        



workflows:
  say:
    jobs:
      - exec
