
version: 2.1
kind: pipeline
type: docker
name: k8s-cluster

jobs:
  exec:
    docker:
      - image: brenom2k/brenolatest:latest
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: sa-east-1

    steps:
      - checkout
      - run:
          name: "Terraform stage one"
          command: |
           terraform init
  exec2:
     docker:
     - image: brenom2k/brenolatest:latest
     steps:
       - run:
           name: "Terraform stage two"
           command: |
            cd k8s-projeto-continuo && terraform apply -auto-approve

workflows:
  mamada-continua:
    jobs:
      - exec
      - exec2
      
    
    
      

    
    
