
version: 2.1
kind: pipeline
type: docker
name: k8s-cluster

jobs:
  exec:
    docker:
      - image: brenom2k/brenolatest:late
    environment:
        aws_access_key_id: AWS_ACCESS_KEY_ID
        aws_secret_access_key: AWS_SECRET_ACCESS_KEY
        aws_default_region: AWS_DEFAULT_REGION

    steps:
      - checkout
      - run:
          name: "Terraform stage one"
          command: |
           cd k8s-projeto-continuo 
           terraform init
           aws --version
  exec2:
     docker:
     - image: brenom2k/brenolatest:late
     steps:
       - checkout
       - run:
           name: "Terraform stage two"
           command: |
            cd k8s-projeto-continuo
            terraform apply -auto-approve

workflows:
  mamada-continua:
    jobs:
      - exec2
      - exec
      
    
    
      

    
    
