
version: 2.1
kind: pipeline
type: docker
name: k8s-cluster

jobs:
  exec:
    docker:
      - image: brenom2k/brenolatest:latest
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: sa-east-1

    steps:
      - checkout
      - run:
          name: "Switch directory and apply terraform resources"
          command: |
           cd k8s-projeto-continuo && terraform apply -auto-approve


workflows:
  say:
    jobs:
      - exec
