
version: 2.1

jobs:
  exec:
    docker:
      - image: brenom2k/brenolatest:latest
    environment:
        AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
        AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
        AWS_DEFAULT_REGION: sa-east-1

    steps:
      - checkout
      - run:
          name: "Switch directory"
          command: "cd k8s-projeto-continuo"



workflows:
  say:
    jobs:
      - exec
