- name: Destroy cluster before starting again
  command: kubeadm reset -f

- name: Initialize k8s cluster
  command: kubeadm init
  register: kubeadm_init_output

- name: Create file with output
  copy:
    content: "{{ kubeadm_init_output.stdout }}"
    dest: /root/kubeadminit

- name: Prepare kubejoin script
  shell: tail -2 /root/kubeadminit > /root/kubejoin.sh

- name: Get kubejoin
  fetch:
    src: /root/kubejoin.sh
    dest: ./join
  
- name: Organize files
  shell: |
        cp join/{{ inventory_hostname }}/root/kubejoin.sh join/  
        rm -fr join/{{ inventory_hostname }}
  delegate_to: localhost
  become: no

- name: Download template calico
  shell: | 
        curl https://docs.projectcalico.org/manifests/calico.yaml -O
  environment: 
    KUBECONFIG: /etc/kubernetes/admin.conf
  become: yes

- name: Apply template calico
  command: kubectl apply -f calico.yaml

  


      

  
